version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2
  lindroid-buildd: lindroid-releng/lindroid-buildd-orb@volatile

jobs:
  setup:
    executor: continuation/default
    resource_class: small
    steps:
      - lindroid-buildd/checkout
      - lindroid-buildd/generate
      - continuation/continue:
          configuration_path: generated_config.yml

workflows:
  setup:
    jobs:
      - setup:
          filters:
            tags:
              only: /^lindroid\/.*\/.*/
